server:
  port: 8080
spring:
  application:
    name: "crediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  r2dbc:
    url: r2dbc:postgresql://192.168.0.16:5432/crediYa
    username: admin
    password: admin
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  profiles:
    include: null
jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci1jcmVkaVlhLWFwcGxpY2F0aW9u
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapters:
  r2dbc:
    host: "192.168.0.16"
    port: 5432
    database: "crediYa"
    schema: "public"
    username: "admin"
    password: "admin"
