server:
  port: 8080
spring:
  application:
    name: "crediYa"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:192.168.0.16}:5432/crediYa
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  flyway:
    enabled: true
    url: jdbc:postgresql://${DB_HOST:192.168.0.16}:5432/crediYa
    user: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  profiles:
    include: null
jwt:
  secret: dGVzdC1zZWNyZXQta2V5LWZvci1jcmVkaVlhLWFwcGxpY2F0aW9u
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "*"

adapters:
  r2dbc:
    host: ${DB_HOST:192.168.0.16}
    port: 5432
    database: crediYa
    schema: public
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}

auth:
  issuer: http://${AUTH_SERVER:localhost}:8080
  audience: crediYa-API
  key:
    id: dGVzdC1zZWNyZXQta2V5LWZvci1jcmVkaVlhLWFwcGxpY2F0aW9u
    generate: false
    private-pem-path: file:/resources/keys/private.pem